#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  proxy_pass         http://127.0.0.1:__PORT__/;

  include proxy_params_no_auth;
  proxy_pass_header  Server;

  client_max_body_size 50M;
  
  # be careful, this line doesn't override any proxy_buffering on set in a conf.d/file.conf
  proxy_buffering off;
  more_set_headers "X-Frame-Options : ALLOWALL";
  proxy_http_version 1.1;                        # recommended with keepalive connections
  
  # WebSocket proxying - from http://nginx.org/en/docs/http/websocket.html
}

location ~* __PATH__/p/[^/]*(_|%|\*)[^/]*/export/etherpad {
    return 404;
}
