#!/bin/bash

# Dependencies for AbiWord
abiword_app_depencencies="abiword"

# Dependencies for LibreOffice
libreoffice_app_dependencies="unoconv libreoffice-writer"

# NodeJS version
nodejs_version=14

# MyPads version
# This variable is mostly used to force an upgrade of the package in case of new versions of MyPads.
mypads_version=1.7.20

# Plugin versions
ep_align_version=0.3.34
ep_author_hover_version=0.3.19
ep_comments_page_version=0.1.60
ep_countable_version=0.0.11
ep_delete_empty_pads_version=0.0.7
ep_font_color_version=0.0.42
ep_headings2_version=0.2.28
ep_markdown_version=0.1.32
ep_page_view_version=0.5.24
ep_spellcheck_version=0.0.27
ep_subscript_and_superscript_version=0.2.26
ep_table_of_contents_version=0.3.20
ep_font_size_version=0.4.22
