#!/bin/bash

# Dependencies for abiword
abiword_app_depencencies="abiword"

# Dependencies for libre office
libreoffice_app_dependencies="unoconv libreoffice-writer"

# NodeJS version
nodejs_version=6

# Mypads version
# This variable is mostly used to force an upgrade of the package in case of new versions of mypads.
mypads_version=1.6.8
