#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=password --value="$password"

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing nodejs..."

ynh_nodejs_install

#=================================================
# CREATE A MYSQL DATABASE
#=================================================
ynh_script_progression "Migrate MySQL database to utf8..."

ynh_mysql_db_shell <<< "ALTER DATABASE $db_name CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"

#=================================================
# HANDLE LOG FILES AND LOGROTATE
#=================================================
ynh_script_progression "Configuring log rotation..."

# Create log directory
mkdir -p /var/log/$app
touch /var/log/$app/etherpad.log
chown $app -R /var/log/$app

#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Configure $app..."

abiword_path="null"
soffice_path="null"

if [[ "$export" == "abiword" ]]
then
    abiword_path="\"$(which abiword)\""
elif [[ "$export" == "libreoffice" ]]
then
    soffice_path="\"$(which soffice)\""
fi

# Use LDAP for MyPads
comment_if_ldap_disabled="//ldap_disabled"
if [ $mypads -eq 1 ] && [ $useldap -eq 1 ]
then
    comment_if_ldap_disabled=""
fi

# Calculate and store the config file checksum into the app settings
ynh_config_add --template="settings.json" --destination="$install_dir/settings.json"
ynh_config_add --template="credentials.json" --destination="$install_dir/credentials.json"

#=================================================
# INSTALL ETHERPAD'S PLUGINS
#=================================================
ynh_script_progression "Installing Etherpad plugins..."

pushd "$install_dir"
  corepack enable
  corepack prepare pnpm@latest --activate
  ynh_hide_warnings ynh_exec_as_app ETHERPAD_PRODUCTION=true bin/installDeps.sh
  ynh_hide_warnings ynh_exec_as_app pnpm run install-plugins \
        ep_align@${ep_align_version} \
        ep_author_hover@${ep_author_hover_version} \
        ep_delete_empty_pads@${ep_delete_empty_pads_version} \
        ep_headings2@${ep_headings2_version} \
        ep_font_size@${ep_font_size_version}
    if [ $mypads -eq 1 ]; then
            ynh_hide_warnings ynh_exec_as_app pnpm run install-plugins ep_mypads@${mypads_version}
    fi
popd

#=================================================
# SOME HACKS
#=================================================

if [ $mypads -eq 1 ]
then
    ynh_script_progression "Tweaking MyPad configuration..."

    # Add a link to Etherpad to allow anonymous pads creation from MyPads.
    ynh_replace --match="^ *\"DESCRIPTION\": .*</ul>" --replace="&<a href=../>Pads anonymes</a>" --file=$install_dir/node_modules/ep_mypads/static/l10n/fr.json
    ynh_replace --match="^ *\"DESCRIPTION\": .*</ul>" --replace="&<a href=../>Anonymous pads</a>" --file=$install_dir/node_modules/ep_mypads/static/l10n/en.json
    # And a link to Etherpad admin from MyPads.
    ynh_replace --match="^ *\"FOOTER\": .*2.0" --replace="& | <a href='../admin'>Etherpad admin</a>" --file=$install_dir/node_modules/ep_mypads/static/l10n/en.json
    ynh_replace --match="^ *\"FOOTER\": .*2.0" --replace="& | <a href='../admin'>Etherpad admin</a>" --file=$install_dir/node_modules/ep_mypads/static/l10n/fr.json

    # Find the /div just after the field to open a pad in order to add a link to MyPads plugin.
    sed -i '157i<center><br><font size="4"><a href="./mypads/" style="text-decoration: none; color: #555">MyPads</a></font></center>' $install_dir/src/templates/index.html
fi

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring systemd service..."

ynh_add_nginx_config

ynh_config_add_systemd

yunohost service add $app --description="Collaborative editor" --log="/var/log/$app/etherpad.log"

ynh_config_add_logrotate

ynh_config_add_fail2ban --logpath="/var/log/nginx/$domain-access.log" --failregex="<HOST> .* .POST /mypads/api/auth/login HTTP/1.1. 400"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting systemd service..."

ynh_systemctl --service=$app --action=restart --log_path=systemd --line_match="Your Etherpad version is"

if [ $mypads -eq 1 ]
then
    ynh_replace --match="__LANGUAGE__" --replace="$language" --file="../conf/lang_mypads.sql"
    ynh_mysql_db_shell < "../conf/lang_mypads.sql"

    # Wait for etherpad to be fully started
    ynh_systemctl --service=$app --action=restart --log_path=systemd --line_match="Your Etherpad version is"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
